# Generated by Django 5.0.2 on 2024-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='yy小迷弟', max_length=20, null=True, verbose_name='用户姓名')),
                ('account', models.CharField(max_length=16, unique=True, verbose_name='用户账号')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('mobile', models.CharField(max_length=32, verbose_name='用户手机号')),
                ('money', models.CharField(max_length=32, unique=True, verbose_name='账户余额')),
            ],
        ),
    ]
