# Generated by Django 5.0.2 on 2024-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_temporary_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='是否已支付'),
        ),
    ]
