# Generated by Django 5.0.2 on 2024-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_temporary_order_is_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0, verbose_name='账户余额'),
        ),
    ]
