# Generated by Django 5.0.2 on 2024-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_order',
            name='userPrizeReceipt',
            field=models.BooleanField(default=False, verbose_name='用户奖品是否已接收'),
        ),
    ]
