# Generated by Django 5.0.2 on 2024-02-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_temporary_order_userprizereceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_shengxiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='开奖时间')),
                ('open_shengxiao', models.CharField(max_length=200, verbose_name='开奖生肖')),
                ('is_edit', models.BooleanField(default=False, verbose_name='是否已人工修改')),
            ],
        ),
    ]
