# Generated by Django 5.0.2 on 2024-02-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_open_shengxiao_current_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_shengxiao',
            name='current_phase',
            field=models.IntegerField(unique=True, verbose_name='目前阶段'),
        ),
        migrations.CreateModel(
            name='user_bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bet_shengxiao', models.CharField(max_length=200, verbose_name='用户购买的生肖')),
                ('user_bet_money', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='用户共赢了多少钱')),
                ('user_bet_time', models.DateTimeField(verbose_name='用户购买生肖时的订单创建时间')),
                ('open_shengxiao', models.CharField(max_length=200, verbose_name='当期开奖的生肖')),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.open_shengxiao', to_field='current_phase', verbose_name='当前期数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户id')),
            ],
        ),
    ]
