# Generated by Django 5.0.2 on 2024-02-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_open_shengxiao_current_phase_user_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_order',
            name='order_create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='订单创建时间'),
        ),
    ]
