# Generated by Django 5.0.2 on 2024-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_temporary_order_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bet',
            name='open_time',
            field=models.DateTimeField(auto_now=True, verbose_name='开奖的时间'),
        ),
    ]
