# Generated by Django 5.0.2 on 2024-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_user_bet_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bet',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='系统是否已支付资金给用户'),
        ),
    ]
